# .github/workflows/main.yml (Definitive Shell-Based Workflow)
name: Run Automated QuantConnect Backtest

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-and-store-backtest:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository Code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install All Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lean
          pip install -r requirements.txt

      - name: 4. Authenticate LEAN CLI
        run: |
          lean login --user-id ${{ secrets.QC_USER_ID }} --api-token ${{ secrets.QC_API_TOKEN }}
        
      - name: 5. Initialize LEAN Workspace (Non-Interactive)
        run: |
          # The "yes |" command automatically answers 'y' to any confirmation prompts.
          # This forces the command to run non-interactively.
          yes | lean init --language python

      - name: 6. Pull Cloud Project
        run: |
          lean cloud pull --project "23708106"

      - name: 7. Run Cloud Backtest
        run: |
          lean backtest "23708106" --output "23708106/backtest-results.json" --detach --no-update

      - name: 8. Store Results in Firestore
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python store_results.py
