# .github/workflows/main.yml
name: Run Automated QuantConnect Backtest

on:
  push:
    branches: [ "main" ] # Runs every time you push to the main branch
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  run-and-store-backtest:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository Code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Run Backtest Script
        env:
          QC_USER_ID: ${{ secrets.QC_USER_ID }}
          QC_API_TOKEN: ${{ secrets.QC_API_TOKEN }}
        run: python run_backtest.py

      - name: 5. Store Results Script
        env:
          QC_USER_ID: ${{ secrets.QC_USER_ID }}
          QC_API_TOKEN: ${{ secrets.QC_API_TOKEN }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python store_results.py
